version: '4.4'
services:
  mongo:
    image: sloopstash/mongo-db:v4.4.18
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo-db-data:/opt/mongo-db/data
      - mongo-db-log:/opt/mongo-db/log
      - /opt/kickstart-docker/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - /opt/kickstart-docker/workload/mongo-db/${MONGODB_VERSION}/conf/supervisor.ini:/opt/mongo-db/system/supervisor.ini
      - /opt/kickstart-docker/workload/mongo-db/${MONGODB_VERSION}/conf/server.conf:/opt/mongo-db/conf/server.conf
    networks:
      common:
        ipv4_address: ${MONGODB_IP}
volumes:
  mongo-db-data:
    driver: local
  mongo-db-log:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${MONGODB_NETWORK}
